version: '3.8'

networks:
  back-tier:
    driver: bridge


services:
  db:
    image: mariadb
    container_name: database
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: bikeapp
      MARIADB_ROOT_PASSWORD: Abc123
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
      - ./csvimport/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m
    networks:
      - back-tier
      

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - '5000:5000'
      - '5001:5001'
    environment:
      - ASPNETCORE_HTTPS_PORT=5000
      - ASPNETCORE_HTTP_PORT=5001
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5000;http://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
    depends_on:
      db:
        condition: service_healthy
    networks:
      - back-tier
    volumes:
      - ./backend/https:/https
    healthcheck:
      test: ["CMD", 'curl', 'https://localhost:5000/health' ]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m



volumes:
  dbdata: