version: '3'

networks:
  back-tier:
    driver: bridge


services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Abc123
      MYSQL_DATABASE: bikeapp
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - back-tier

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    restart: unless-stopped
    ports:
      - 8081:80
    networks:
      - back-tier

volumes:
  dbdata: