version: '3'

networks:
  back-tier:
    driver: bridge


services:
  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      - ASPNETCORE_HTTPS_PORT=5000
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    networks:
      - back-tier
    volumes:
      - ~/.aspnet/https:/https:ro

  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Abc123
      MYSQL_DATABASE: bikeapp
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - back-tier

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    restart: unless-stopped
    ports:
      - 8081:80
    networks:
      - back-tier

volumes:
  dbdata: