SET GLOBAL innodb_buffer_pool_size=524288000;
SET GLOBAL max_allowed_packet=524288000;

CREATE TABLE IF NOT EXISTS Stations (
    FID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID VARCHAR(255) NOT NULL UNIQUE KEY,
    NameFIN VARCHAR(255) NOT NULL,
    NameSWE VARCHAR(255) NOT NULL,
    NameENG VARCHAR(255) NOT NULL,
    AddressFIN VARCHAR(255) NOT NULL,
    AddressSWE VARCHAR(255) NOT NULL,
    CityFIN VARCHAR(255) NOT NULL,
    CitySWE VARCHAR(255) NOT NULL,
    Operator VARCHAR(255)NOT NULL,
    Capacity INT NOT NULL,
    Longitude VARCHAR(255) NOT NULL,
    Latitude VARCHAR(255) NOT NULL
);