import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('button', { name: 'open drawer' }).click();
  await page.getByRole('button', { name: 'Journeys' }).click();
  await page.getByRole('cell', { name: 'Laajalahden aukio' }).click();
  await page.getByRole('cell', { name: 'Teljäntie' }).click();
  await page.getByRole('cell', { name: '2.04 km' }).click();
  await page.getByRole('cell', { name: '8.33 min' }).click();
  await page.getByRole('button', { name: 'Page 312772' }).click();
  await page.getByRole('cell', { name: 'Muusantori' }).click();
  await page.getByRole('cell', { name: 'Torpanranta' }).click();
  await page.getByRole('cell', { name: '2.14 km' }).click();
  await page.getByRole('cell', { name: '6.90 min' }).click();
  await page.getByPlaceholder('Search').click();
  await page.getByPlaceholder('Search').fill('pasila');
  await page.locator('#orderBy').selectOption('departureStationName');
  await page.locator('#orderDir').selectOption('desc');
  await page.locator('#minDistance').click();
  await page.locator('#minDistance').fill('10');
  await page.locator('#maxDistance').click();
  await page.locator('#maxDistance').fill('100');
  await page.locator('#minDuration').click();
  await page.locator('#minDuration').fill('10');
  await page.locator('#maxDuration').click();
  await page.locator('#maxDuration').fill('100');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('row', { name: 'Pasilan asema Pasilan asema 0.03 km 0.28 min' }).getByRole('cell', { name: 'Pasilan asema' }).first().click();
  await page.getByRole('row', { name: 'Pasilan asema Pasilan asema 0.03 km 0.28 min' }).getByRole('cell', { name: 'Pasilan asema' }).nth(1).click();
  await page.getByRole('cell', { name: '0.03 km' }).click();
  await page.getByRole('cell', { name: '0.28 min' }).click();
  await page.getByRole('button', { name: 'Reset' }).click();
  await page.getByRole('cell', { name: 'Laajalahden aukio' }).click();
  await page.getByRole('cell', { name: 'Teljäntie' }).click();
  await page.getByRole('cell', { name: '2.04 km' }).click();
  await page.getByRole('cell', { name: '8.33 min' }).click();
  await page.getByRole('button', { name: 'Home' }).click();
});