import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('button', { name: 'open drawer' }).click();
  await page.getByRole('button', { name: 'Journeys' }).click();
  await page.locator('button').nth(1).click();
  await page.getByRole('button', { name: 'Next page' }).click();
  await page.getByRole('button', { name: 'Previous page' }).click();
  await page.getByPlaceholder('Search').click();
  await page.getByPlaceholder('Search').fill('pasila');
  await page.locator('#orderBy').selectOption('departureStationName');
  await page.locator('#orderDir').selectOption('desc');
  await page.locator('#limit').selectOption('20');
  await page.locator('#minDistance').click();
  await page.locator('#minDistance').fill('10');
  await page.locator('#maxDistance').click();
  await page.locator('#maxDistance').fill('100');
  await page.locator('#minDuration').click();
  await page.locator('#minDuration').fill('10');
  await page.locator('#maxDuration').click();
  await page.locator('#maxDuration').fill('100');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('row', { name: 'Pasilan asema Pasilan asema 0.03 km 0.28 min' }).getByRole('cell', { name: '0.03 km' }).click();
  await page.getByRole('cell', { name: '0.28 min' }).click();
  await page.getByRole('button', { name: 'Next page' }).click();
  await page.getByRole('button', { name: 'Page 6' }).click();
  await page.getByRole('button', { name: 'Reset' }).click();
  await page.getByRole('button', { name: 'Next page' }).click();
  await page.getByRole('button', { name: 'Page 312772' }).click();
  await page.getByRole('button', { name: 'open drawer' }).click();
  await page.getByRole('button', { name: 'Home' }).click();
  await page.getByRole('button').first().click();
});